### ISSUE TITLE
Type: Minor typo at landing page

### ISSUE THREAD

**Issue by muhammedanaskhan** [CreoWis/hashnode-client#10]
## Minor typo in Hashnode's spelling at landing page

Screenshot : 
![hashnode_typo](https://github.com/CreoWis/hashnode-client/assets/72510634/08777cda-1587-46ab-8b5d-3997253c37fd)

## I adhere to the CODE OF CONDUCTS of this project
- [✓ ] I DO

**Comment by muhammedanaskhan** [comment]
Kindly assign me task to fix this and help kickstart my journey as a contributor, thanks

**Comment by muhammedanaskhan** [comment]
Also there's a typo in "DAIRIES" spelling as well at same component

**Comment by atapas** [comment]
> Also there's a typo in "DAIRIES" spelling as well at same component

Please raise a PR with both.
