### ISSUE TITLE
[Feature Request]: add repo-rater GitHub Action

### ISSUE THREAD

**Issue by CBID2** [CreoWis/hashnode-client#11]
## Why Do We Need This Feature?

Krish recently created this GitHub Action in connection with Eddie Jaoude’s new project, Repo-Rater: https://github.com/marketplace/actions/repo-rater-action
This can help the project gain more visibility.

## Are There Any Workarounds Available Today?
N/A

## Any Design Proposals(Here you can provide any raw screenshots)
N/A

## I adhere to the CODE OF CONDUCTS of this project
- [x] I DO

**Comment by atapas** [comment]
Do you want to work on this? It's a good proposal. @CBID2
